### ISSUE TITLE
Add link to ASE

### ISSUE THREAD

**Issue by ai** [dfernandez79/postcss-ase-colors#1]

**Comment by dfernandez79** [comment]
Hi @ai, I couldn't find a good reference about ASE files to link. Because of that I've added a little bit more of information. ASE are color palette files used mainly in Adobe products.

The goal of this plugin is to streamline the designer-ui developer workflow. Color standards are hard to maintain, because graphic designers usually copy & paste color HEX values by hand :( ... if you can use the same palette file directly things are more smooth.

Hope that helps, let me know if I can close this issue or you were expecting something more.

**Comment by jonathantneal** [comment]
I think you resolved the issue and this can be closed.
